### ISSUE TITLE
Altair 1.3.0 after the update seems to make Terminus unusable

### ISSUE THREAD

**Issue by 111andre111** [yxuko/terminus-altair#18]
After I disabled it Terminus was working again.

Here first without Altair:
![2021-04-17 12_53_21-Settings](https://user-images.githubusercontent.com/48132449/115110537-38a48800-9f7c-11eb-8e7e-0a62a7abdf8e.png)
And now with Altair
![2021-04-17 12_53_42-Settings](https://user-images.githubusercontent.com/48132449/115110546-46f2a400-9f7c-11eb-8b34-097ea5f997ae.png)
Any idea what might cause this?

@yxuko

**Comment by yxuko** [comment]
Hello, I will check it out

**Comment by yxuko** [comment]
I issued a new version 1.5.0 and it should be fixed now.
Let me know if it is working again and Thank you.

**Comment by 111andre111** [comment]
Thank you for the extremely fast reaction @yxuko it's working.
